-- LOAD DATA LOCAL INFILE 'users.csv'
-- INTO TABLE users
-- FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n'
-- IGNORE 1 LINES;


-- LOAD DATA LOCAL INFILE 'boxes.csv'
-- INTO TABLE boxes
-- FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n'
-- IGNORE 1 LINES;


-- LOAD DATA LOCAL INFILE 'contents.csv'
-- INTO TABLE contents
-- FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n'
-- IGNORE 1 LINES;


-- LOAD DATA LOCAL INFILE 'qr_codes.csv'
-- INTO TABLE qr_codes
-- FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n'
-- IGNORE 1 LINES;


