-- DELIMITER ;;
-- DROP PROCEDURE IF EXISTS inventory_string;

-- CREATE PROCEDURE inventory_string(string_filter VARCHAR(255))
-- BEGIN
--     SELECT 
--         p.product_id AS "ID", p.name AS "Name", i.location AS "Shelf", i.quantity AS "Quantity"
--     FROM
--         inventory AS i
--     LEFT JOIN product AS p ON p.product_id = i.product_id
--     WHERE p.name = string_filter;
-- END
-- ;;
-- DELIMITER ;